### ISSUE TITLE
Translate program in Italian

### ISSUE THREAD

**Issue by bovirus** [drweb86/butil#171]
@drweb86 

Which is the language file that contains GUI strings?

Is enought to localzie the file 

[Resources.resx](https://github.com/drweb86/butil/blob/master/sources/butil/Localization/Resources.resx)

and save it as 'Resources.it.resx'

For the installer trabsate the file

https://github.com/drweb86/butil/blob/master/sources/Setup/BUtil-Default.isl

as 'BUtil-Italian.iss' translating only messages?

Why are you using separae .iss for each language?

**Comment by drweb86** [comment]
Hi @bovirus .

Thanks for interest in localization. 

There were 3 resource files. I've merged them into one today in BUtil.Core. And updated CustomMessages in Inno Setup - putting alltogether into one file. 

`Is enought to localzie the file
[Resources.resx](https://github.com/drweb86/butil/blob/master/sources/butil/Localization/Resources.resx)
and save it as 'Resources.it.resx'`
Yes. 

I need to go through all localization strings to remove obsolte ones since I didn't do it for years. And some labels became outdated since I added import of photos several days ago. I'm planning to do it today-tomorrow. I'll write to you one it will be completed.

**Comment by bovirus** [comment]
@drweb86 

I created the italian language

https://github.com/drweb86/butil/pull/172

Please merge my PR.

After I will open a new PR iinstaller issues.

**Comment by drweb86** [comment]
Hi @bovirus .

I finished updating localization. Now it fits with import photos task (no backup words everywhere), also it uses nowadays practice for key naming - to have context, like name of entity inside. And I removed all obsolete keys.

**Comment by drweb86** [comment]
> Question: which version is your Inno Setup program?
> What type? Unicode I believe?
6.2.1 . I guess its Unicode.

> Have you the standard language files (.isl) in "Language" subfoolders in Inno Setup?
I've updated setup script, so now translations are inside single iss file.

**Comment by drweb86** [comment]
If you want update your MR. Now everything in it looks like as it should be.

**Comment by bovirus** [comment]
@drweb86 

It's a very complex job if you continue to change the list of strings.
Otherwise pelas etell em when you will finish and I cannot check:
Otehrwise it's a compelx and boring job.
Now your language file is lshoretd of 5 Kb then previous.

**Comment by drweb86** [comment]
Hi @bovirus .

I think we have miscommunication here.
I said yesterday that I was going to rework translation and write to you once it will be completed.

> I'm planning to do it today-tomorrow. I'll write to you one it will be completed.

I finished this work today and wrote to you.

> I finished updating localization.

The reason why I spent yesterday and today to rework localization is because in general translation approach was outdated regarding key names, and also there were lots of duplicates and I had to perform lots of renames since last week when new type of task was added. 

I see you did not wait and make 2 MRs and spent time. While I appreciate your efforts, I still think that you should've listened to me.

**Comment by bovirus** [comment]
@drweb86

YOU CHANGED TRANSLATION TWO TIMES!!! IN A  VERY SHORT TIME!!!

After you said that you are working on a new relase you released a new version without mention that is not final version.

If the version of language file was not final why did you release an internediate version that is completly differnt from first, and then you released a third new version that is differnt from first and second?

Is not real and good to change enaything about translationa and destroy any previous version of translation.

I believe that what you want to do, in which direction you want to go, and wiythout change direction evry time.

You did the same for language files and installer (.,iss script).

I'm intersted to work again on translation only if you confirm that you never change again the reference id of strings now and in the future.
You will just add strings.
This to avoid tyo destroy aagain my job that cost me some spare time.

**Comment by drweb86** [comment]
Hi

I've finished code revision. I'm not planning to change IDs in the nearest future. But I cannot guarantee that. Over a decade approach to localization was updated 3 times already.
